### ISSUE TITLE
Add pop-up lists for Reservation Names, Watersheds, States, and Document Types to Digital Commons metadata form

### ISSUE THREAD

**Issue by karlbenedict** [nawrs/nawrs#11]

**Comment by karlbenedict** [comment]
Google spreadsheet with the various reference lists: https://docs.google.com/a/nawrs.net/spreadsheets/d/1ItdW0-w1U2e1m8CEx-8imTrhfJ1qkS-PJXQ1SKGE7n4/edit?usp=sharing

**Comment by jonathanwheeler01** [comment]
Ticket for this feature submitted to BePress 5/12.

**Comment by jonathanwheeler01** [comment]
Closing. We will make sure the existing metadata have all been copied to the new lists.
