### ISSUE TITLE
repository display

### ISSUE THREAD

**Issue by dmc793** [nawrs/nawrs#13]
The organization of the webpage is by document date.  It should display by settlement name as was done in LoboVault. (If this is already in the issues,  pls disregard)

**Comment by jonathanwheeler01** [comment]
Ticket for this change submitted to BePress 5/12.

**Comment by jonathanwheeler01** [comment]
Update - we're going to have to redo the NAWRS community and create settlement sub-collections, which is how it was done in LoboVault.

**Comment by dmc793** [comment]
Ok

Sent from my iPhone

On May 30, 2017, at 8:23 AM, Jonathan Wheeler <notifications@github.com<mailto:notifications@github.com>> wrote:


Update - we're going to have to redo the NAWRS community and create settlement sub-collections, which is how it was done in LoboVault.

-

**Comment by dmc793** [comment]
Hi Jon, do you need me to do anything on this? Do you have an eta? thx d

________________________________

**Comment by jonathanwheeler01** [comment]
Should be done: http://digitalrepository.unm.edu/nawrs_comm/

**Comment by dmc793** [comment]
Wooo Hoooo!! thanks
