### ISSUE TITLE
Tribes field

### ISSUE THREAD

**Issue by dmc793** [nawrs/nawrs#15]
Contains only one tribe when there are several. Ex.  Aamodt lists only Tesuque Pueblo and omits San Ildefonso, Pojoaque & Nambe Pueblos

**Comment by jonathanwheeler01** [comment]
I submitted a request to have data entry for this field changed to a dropdown list with multiple selections enabled. We will have to see what's available and may have to batch revise using existing LoboVault metadata.

**Comment by jonathanwheeler01** [comment]
Closing.
