### ISSUE TITLE
Need another doc type

### ISSUE THREAD

**Issue by dmc793** [nawrs/nawrs#18]
Settlement Agreement & State Legislation

Or some other way to indicate that some docs have a dual purpose. (this is the only one so far)

**Comment by jonathanwheeler01** [comment]
Change request submitted to BePress.

**Comment by dmc793** [comment]
yayaya its there, now if we search on either term  - Settlement Agreement or State Legislation - will it show up? Tx D

________________________________

**Comment by jonathanwheeler01** [comment]
The basic search matches against any terms, so someone entering either term should get all the corresponding results. The advanced search is a little more refined, but I notice that searching on "settlement agreement" returned results with document types of "post-settlement agreement," so it looks like using either term individually will work fine.

**Comment by dmc793** [comment]
Thanks Jon appreciate it

Sent from my iPhone

On May 22, 2017, at 9:30 AM, Jonathan Wheeler <notifications@github.com<mailto:notifications@github.com>> wrote:


The basic search matches against any terms, so someone entering either term should get all the corresponding results. The advanced search is a little more refined, but I notice that searching on "settlement agreement" returned results with document types of "post-settlement agreement," so it looks like using either term individually will work fine.

-

**Comment by jonathanwheeler01** [comment]
Sounds good - I will close this issue but we can create a new one if the search/fields aren't intuitive.
