### ISSUE TITLE
Labeling

### ISSUE THREAD

**Issue by dmc793** [nawrs/nawrs#24]
Need to label reservations, & hydrological units

**Comment by jonathanwheeler01** [comment]
Can do - I'm concerned that adding static labels would clutter the map. Currently, if a user clicks on a feature then the name is provided in a pop-up. We might be able to have the name appear when a user hovers the mouse over a feature. Do you want to try that first?

**Comment by dmc793** [comment]
Lets try the hover option.  When a person is looking at the map and if there are several reservations displayed, it can  be impossible to tell which is which Thanks d

**Comment by jonathanwheeler01** [comment]
Done for reservations ("tribal lands with associated documents" - the ones that show up in red). This is a quick update which can be applied to other layers - watersheds, states, etc. I'd be concerned about the usability impact of a lot of mouseover actions, but if additional labels are needed we can explore the options.

Going to close this issue for now, but can re-open as needed.

**Comment by dmc793** [comment]
J I think the reservations are the most important thing and we should wait and see if the others are needed.  The states are there if you look hard enough Tx D
