### ISSUE TITLE
Opening page of repostitory 

### ISSUE THREAD

**Issue by dmc793** [nawrs/nawrs#25]
This page should arrange the documents by settlement (see old page) rather than by date added to collection

**Comment by jonathanwheeler01** [comment]
We added a new community to organize the documents by settlement - please have a look at http://digitalrepository.unm.edu/nawrs_comm/ to make sure that's correct. We need to manually add new documents to their correct settlement collection, so recently uploaded items may not show up in their settlements. 

The documents at http://digitalrepository.unm.edu/nawrs/ are always going to show up in chronological order. We can hide this collection to prevent confusion if you like. 

Closing, but I can reopen as needed. Thanks!

**Comment by dmc793** [comment]
Hi Jon, The last months have been a wild ride for the family. I just took at look at the new set up for the page, and it looks perfect.  You mentioned that recently uploaded files might not appear in the settlements.  I have not uploaded any new files since the summer. do you think these are included?  You mentioned that the new files will have to be added manually.  Do you want me to do that? if so how is it done.  I will be continuing at a snail's pace, but continuing none the less. Thanks ever so Darcy

________________________________

**Comment by dmc793** [comment]
Yes, lets hid the chron collection as it has little meaning for the public. Thanks d

________________________________

**Comment by dmc793** [comment]
Good idea on hiding the chronological page.

Sent from my iPhone

On Dec 30, 2017, at 3:27 PM, Jonathan Wheeler <notifications@github.com<mailto:notifications@github.com>> wrote:


We added a new community to organize the documents by settlement - please have a look at http://digitalrepository.unm.edu/nawrs_comm/ to make sure that's correct. We need to manually add new documents to their correct settlement collection, so recently uploaded items may not show up in their settlements.

The documents at http://digitalrepository.unm.edu/nawrs/ are always going to show up in chronological order. We can hide this collection to prevent confusion if you like.

Closing, but I can reopen as needed. Thanks!

**Comment by jonathanwheeler01** [comment]
I changed the configuration to hide that collection. The system is taking a while to finish the update, but it should go through today.

**Comment by jonathanwheeler01** [comment]
Also, "manual" wasn't the best word choice. I have to run a script to add new documents from Digital Commons to the mapper, but that's a click of a button and only takes a few minutes. But there's no change in the process on your end.

**Comment by dmc793** [comment]
Thanks Jon. Appreciate it d

Sent from my iPhone

On Feb 22, 2018, at 3:28 PM, Jonathan Wheeler <notifications@github.com<mailto:notifications@github.com>> wrote:


Also, "manual" wasn't the best word choice. I have to run a script to add new documents from Digital Commons to the mapper, but that's a click of a button and only takes a few minutes. But there's no change in the process on your end.

-

**Comment by dmc793** [comment]
Hi there, I checked around 11:30pm & the link on the Nawrs repository page still shows as sorted chron.  Does it take a while for the change to take hold?


I have been wrestling with settlements like the Aamodt settlement which involve more than one tribe/reservation.  Do I do an entry for each doc for each tribe? that would allow me to have separate boundaries and geo centers for each.  Or do I do something else. here are the settlements with multiple reservations that I have ided so far


San Luis Rey:  La Jolla Band of Luiseño Mission Indians of the La Jolla Reservation, Pala Band of Luiseño Mission Indians of the Pala Reservation, Pauma Band of Luiseño Mission Indians of the Pauma and Yuima Reservation, Rincon Band of Luiseño Mission Indians of the Rincon Reservation, San Pasqual Band of Diegueño Mission Indians of California


Aamodt: Pueblo of Nambe, Pueblo of Pojoaque, Pueblo of San Ildefonso, Pueblo of Tesuque (NM)


Seminole of Florida: Reservations for Dania, Big Cypress, Hollywood, Brighton & Tampa




________________________________
